const express=require('express'); const cors=require('cors'); const dotenv=require('dotenv'); dotenv.config();
const app=express(); app.use(cors()); app.use(express.json());
const PORT=+(process.env.AIRPORTFLOW_PORT||8787), BASE=process.env.AERODATABOX_BASE_URL||'https://aerodatabox.p.rapidapi.com', HOST=process.env.AERODATABOX_RAPIDAPI_HOST||'aerodatabox.p.rapidapi.com';
const KEY=()=>process.env.AERODATABOX_RAPIDAPI_KEY, cache=new Map(), CACHE=+(process.env.FLIGHT_CACHE_MS||300000), BOARD_CACHE=+(process.env.DEPARTURE_CACHE_MS||300000);
const first=(...x)=>x.find(v=>v!==undefined&&v!==null&&String(v).trim()!=='')??'', clean=v=>v==null?'':String(v).trim();
function time(v=''){const s=clean(v),m=s.match(/(?:T|\s)(\d{2}:\d{2})|^(\d{1,2}:\d{2})/);return m?(m[1]||m[2]):s} function date(v=''){return clean(v).match(/(\d{4}-\d{2}-\d{2})/)?.[1]||''}
function move(m={}){const a=m.airport||{},sch=first(m.scheduledTime?.local,m.scheduledTimeLocal,m.scheduledTime?.utc),rev=first(m.revisedTime?.local,m.revisedTimeLocal,m.predictedTime?.local),act=first(m.actualTime?.local,m.actualTimeLocal);return{airport:first(a.iata,a.icao),airportName:first(a.name,a.shortName),city:first(a.municipalityName,a.municipality),countryCode:first(a.countryCode),scheduledTime:time(sch),scheduledDate:date(sch),estimatedTime:time(rev),actualTime:time(act),terminal:first(m.terminal),gate:first(m.gate),checkIn:first(m.checkInDesk,m.checkIn),baggage:first(m.baggageBelt,m.baggageCarousel,m.baggage)}}
function norm(f,req=''){return{flightNumber:first(f.number,req).replace(/\s/g,''),airline:first(f.airline?.name),airlineCode:first(f.airline?.iata),status:first(f.status,'Scheduled'),aircraft:first(f.aircraft?.model,f.aircraft?.type),aircraftRegistration:first(f.aircraft?.reg,f.aircraft?.registration),departure:move(f.departure||{}),arrival:move(f.arrival||{})}}
function chicagoDate(){
  const parts=new Intl.DateTimeFormat('en-US',{
    timeZone:'America/Chicago',
    year:'numeric',
    month:'2-digit',
    day:'2-digit'
  }).formatToParts(new Date());
  const get=(type)=>parts.find(p=>p.type===type)?.value;
  return `${get('year')}-${get('month')}-${get('day')}`;
}
async function adb(path){const r=await fetch(BASE+path,{headers:{'X-RapidAPI-Key':KEY(),'X-RapidAPI-Host':HOST,accept:'application/json'},signal:AbortSignal.timeout(20000)});const b=await r.json().catch(()=>null);if(!r.ok){const e=new Error(b?.message||b?.detail||`AeroDataBox returned ${r.status}`);e.status=r.status;throw e}return b}
function seatGuess(s=''){s=String(s).toUpperCase();if(/A380/.test(s))return 500;if(/777/.test(s))return 320;if(/A350/.test(s))return 300;if(/787/.test(s))return 260;if(/A321/.test(s))return 190;if(/A320|737/.test(s))return 170;if(/E17|E19|CRJ/.test(s))return 80;return 160}
function boardFlight(f,kind){const x=norm(f),mv=kind==='departures'?x.departure:x.arrival,seats=seatGuess(x.aircraft),international=x.departure.countryCode&&x.arrival.countryCode&&x.departure.countryCode!==x.arrival.countryCode;return{...x,terminal:mv.terminal,gate:mv.gate,scheduledTime:mv.scheduledTime,revisedTime:mv.estimatedTime,seats,originatingTravelers:kind==='departures'?Math.round(seats*.86*.72):0,international:Boolean(international)}}
async function airportBoard(req,res,kind){if(!KEY())return res.status(503).json({error:'AirportFlow API key is not configured.'});const hours=Math.max(1,Math.min(8,+req.query.hours||4)),force=req.query.force==='1',ck=`${kind}:${hours}`,old=cache.get(ck);if(!force&&old&&Date.now()-old.at<BOARD_CACHE)return res.json(old.data);try{const direction=kind==='departures'?'Departure':'Arrival',offset=kind==='arrivals'?-60:0,qs=new URLSearchParams({offsetMinutes:String(offset),durationMinutes:String(hours*60),withLeg:'true',direction,withCancelled:'false',withCodeshared:'false',withCargo:'false',withPrivate:'false'});const body=await adb(`/flights/airports/iata/ORD?${qs}`),raw=body?.[kind]||[],seen=new Set(),list=[];for(const f of raw){const x=boardFlight(f,kind),id=[x.aircraftRegistration||'',x.scheduledTime,x.departure.airport,x.arrival.airport].join('|');if(x.aircraftRegistration&&seen.has(id))continue;seen.add(id);list.push(x)}const data={[kind]:list,fetchedAt:new Date().toISOString(),rawRecords:raw.length,physicalFlights:list.length};cache.set(ck,{at:Date.now(),data});res.json(data)}catch(e){res.status(e.status===404?404:502).json({error:e.message})}}
app.get('/api/airports/ORD/departures',(q,s)=>airportBoard(q,s,'departures')); app.get('/api/airports/ORD/arrivals',(q,s)=>airportBoard(q,s,'arrivals'));
app.get('/api/flights/:n',async(req,res)=>{if(!KEY())return res.status(503).json({error:'AirportFlow API key is not configured.'});const n=String(req.params.n).toUpperCase().replace(/[^A-Z0-9]/g,''),d=chicagoDate(),ck=`f:${n}:${d}`,old=cache.get(ck);if(old&&Date.now()-old.at<CACHE)return res.json(old.data);try{const body=await adb(`/flights/number/${n}/${d}?withAircraftImage=false&withLocation=false`),list=Array.isArray(body)?body:[],f=list.find(x=>clean(x.number).replace(/\s/g,'').toUpperCase()===n)||list[0];if(!f)return res.status(404).json({error:`No ${n} flight found for ${d}.`});const data={flight:norm(f,n),fetchedAt:new Date().toISOString()};cache.set(ck,{at:Date.now(),data});res.json(data)}catch(e){res.status(e.status===404?404:502).json({error:e.message})}});
app.get('/api/health',(_q,r)=>r.json({ok:true,configured:Boolean(KEY())})); app.listen(PORT,'0.0.0.0',()=>console.log(`AirportFlow API: http://0.0.0.0:${PORT}`));
